name: Org Checkov
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_call:

jobs:
  check-markdown:
    uses: Coalfire-CF/Actions/.github/workflows/org-checkov.yml@main